version: '3.1'

services:
  neodb:
    container_name: neodb
    expose:
      - 7687
      - 7474
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - '$HOME/neo4j/data:/data'
      - '$HOME/neo4j/logs:/logs'
      - '$HOME/neo4j/import:/var/lib/neo4j/import'
      - '$HOME/neo4j/plugins:/plugins'
    environment:
      - NEO4J_AUTH=neo4j/test
    image: neo4j
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper-service
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker-service
    ports:
      # To learn about configuring Kafka for access across networks see
      # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

volumes:
  db:
    driver: local